PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

INSERT OR IGNORE INTO user (id, email, name) VALUES (1, 'admin@example.com', 'Admin User');
INSERT OR IGNORE INTO tree (id, name, description, created_by) VALUES (1, 'Patel Family Tree', 'Main family tree', 1);
INSERT OR IGNORE INTO tree_member (tree_id, user_id, role) VALUES (1, 1, 'owner');

INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (88, 1, 'Aarth', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (69, 1, 'Devanshi', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (68, 1, 'Harshil', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (77, 1, 'Hasmukh', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (76, 1, 'Jaswant', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (81, 1, 'Kajal', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (87, 1, 'Kamini', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (80, 1, 'Kirti', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (89, 1, 'Krishna', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (79, 1, 'Pratibha', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (82, 1, 'Priyeash', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (67, 1, 'Rajesh', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (66, 1, 'Rita', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (86, 1, 'Shivaansh', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (78, 1, 'Vijay', 'Amin', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (85, 1, 'Zalak', 'Amin', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (50, 1, 'Aarav', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (111, 1, 'Aayan', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (160, 1, 'Ajay', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (131, 1, 'Amit', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (150, 1, 'Amita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (142, 1, 'Anal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (177, 1, 'Anita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (138, 1, 'Anjana', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (10, 1, 'Atul', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (165, 1, 'Bal Krishna', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (53, 1, 'Balu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (191, 1, 'Bhadresh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (75, 1, 'Bharat', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (134, 1, 'Bharti', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (118, 1, 'Bipin', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (21, 1, 'Channa', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (57, 1, 'Chetna', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (135, 1, 'Chiman', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (16, 1, 'Dahi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (17, 1, 'Dahya', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (83, 1, 'Deep', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (91, 1, 'Deepa', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (56, 1, 'Deepak', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (44, 1, 'Devarsh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (18, 1, 'Dhai', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (124, 1, 'Dharmesh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (41, 1, 'Dhumil', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (122, 1, 'Dhwani', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (36, 1, 'Diyakanta', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (156, 1, 'Falguni', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (3, 1, 'Girish', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (176, 1, 'Girish', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (182, 1, 'Girish', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (28, 1, 'Haimil', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (110, 1, 'Hani', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (178, 1, 'Happy', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (159, 1, 'Harshal', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (46, 1, 'Harshini', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (19, 1, 'Ichhabhai', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (97, 1, 'Illa', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (185, 1, 'Illa', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (93, 1, 'Ishwar', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (121, 1, 'Jay', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (74, 1, 'Jayanti', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (186, 1, 'Jinal (Chaki)', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (100, 1, 'Jitendra', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (84, 1, 'Jiyan', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (139, 1, 'Jyoti', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (24, 1, 'Kamlaba', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (12, 1, 'Kanti', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (153, 1, 'Kanti', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (95, 1, 'Kanu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (112, 1, 'Kanu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (55, 1, 'Kaushik', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (109, 1, 'Kavita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (61, 1, 'Ketan', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (27, 1, 'Keyur', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (43, 1, 'Kinnari', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (11, 1, 'Krishna', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (29, 1, 'Krishna', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (127, 1, 'Krush', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (166, 1, 'Kushi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (35, 1, 'Laliita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (170, 1, 'Lalita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (33, 1, 'Mahendra', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (101, 1, 'Mahesh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (174, 1, 'Mahesh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (117, 1, 'Mahir', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (0, 1, 'Malav', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (6, 1, 'Mamta', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (180, 1, 'Mangu', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (151, 1, 'Manthan', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (119, 1, 'Manu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (133, 1, 'Manu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (25, 1, 'Margabhai', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (130, 1, 'Masum', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (99, 1, 'Mayank', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (173, 1, 'Meena', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (187, 1, 'Meet', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (140, 1, 'Moksh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (155, 1, 'Munni', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (116, 1, 'Naman', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (145, 1, 'Nandu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (164, 1, 'Naresh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (175, 1, 'Naresh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (161, 1, 'Nikki (Anushree)', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (125, 1, 'Nisha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (98, 1, 'Pankaj', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (106, 1, 'Pankti', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (162, 1, 'Param', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (126, 1, 'Pari', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (2, 1, 'Parul', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (45, 1, 'Payal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (49, 1, 'Payal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (107, 1, 'Payal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (168, 1, 'Pinakin', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (188, 1, 'Pinkal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (103, 1, 'Pintu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (34, 1, 'Pradeep', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (62, 1, 'Pragnya', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (114, 1, 'Prakash', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (148, 1, 'Prakash', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (1, 1, 'Prashant', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (40, 1, 'Pratik', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (163, 1, 'Pruthav', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (63, 1, 'Purvi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (105, 1, 'Ragini', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (120, 1, 'Ramila', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (171, 1, 'Rannchod', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (90, 1, 'Rashmikant', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (108, 1, 'Rasik', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (128, 1, 'Rati', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (102, 1, 'Ravin', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (157, 1, 'Rinku', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (158, 1, 'Roma', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (192, 1, 'Rupal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (141, 1, 'Rupesh', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (184, 1, 'Rutvik', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (48, 1, 'Sachin', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (65, 1, 'Sahil', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (38, 1, 'Sangeeta', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (39, 1, 'Sanjay', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (129, 1, 'Sarda', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (146, 1, 'Savita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (5, 1, 'Seema', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (152, 1, 'Sejal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (64, 1, 'Shail', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (136, 1, 'Shanta', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (181, 1, 'Shanti', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (147, 1, 'Sharda', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (115, 1, 'Sheetal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (132, 1, 'Shobhit', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (143, 1, 'Shrujal', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (13, 1, 'Sita', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (183, 1, 'Soha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (54, 1, 'Subhadra', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (37, 1, 'Sudha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (4, 1, 'Sumitra', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (22, 1, 'Surajba', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (154, 1, 'Sushila', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (144, 1, 'Swapnil', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (169, 1, 'Tulsi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (104, 1, 'Usha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (113, 1, 'Usha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (123, 1, 'Usha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (172, 1, 'Usha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (59, 1, 'Vamanshi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (58, 1, 'Varun', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (42, 1, 'Vatsal', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (167, 1, 'Ved', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (92, 1, 'Vedang', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (47, 1, 'Veena', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (179, 1, 'Vidhi', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (96, 1, 'Vijay', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (137, 1, 'Vijay', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (149, 1, 'Vipul', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (189, 1, 'Vishnu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (190, 1, 'Vishnu', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (14, 1, 'Vitthal', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (15, 1, 'Vitthal', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (23, 1, 'Vitthal', 'Patel', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (60, 1, 'Zamyasha', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (94, 1, 'jyoti', 'Patel', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (30, 1, '', 'Purohit', 'O', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (70, 1, 'Chandrakant', 'Purohit', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (73, 1, 'Hemant', 'Purohit', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (71, 1, 'Kailash', 'Purohit', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (7, 1, 'Kamlesh', 'Purohit', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (8, 1, 'Mansi', 'Purohit', 'F', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (9, 1, 'Priyank', 'Purohit', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (72, 1, 'Yogesh', 'Purohit', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (31, 1, 'Aditya', 'Shah', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (32, 1, 'Kiaan', 'Shah', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (51, 1, 'Mayank', 'Shah', 'M', 1);
INSERT OR IGNORE INTO person (id, tree_id, first_name, last_name, gender, is_living) VALUES (52, 1, 'Sona', 'Shah', 'F', 1);
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 1, 2, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 12, 13, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 3, 4, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 15, 16, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 17, 18, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 21, 22, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 23, 24, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 5, 10, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 6, 7, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 29, 31, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 33, 37, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 38, 41, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 39, 43, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 40, 45, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 34, 47, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 48, 49, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 51, 52, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 53, 54, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 55, 57, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 58, 59, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 61, 62, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 56, 63, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 66, 67, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 70, 71, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 36, 76, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 77, 80, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 81, 83, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 82, 85, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 78, 87, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 88, 89, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 79, 90, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 91, 92, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 35, 93, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 94, 101, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 95, 104, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 96, 105, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 97, 108, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 98, 109, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 27, 110, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 112, 113, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 114, 115, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 118, 120, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 121, 122, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 119, 123, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 124, 125, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 128, 129, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 130, 131, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 133, 134, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 135, 136, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 137, 139, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 138, 141, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 145, 146, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 145, 147, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 148, 150, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 153, 154, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 156, 160, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 155, 164, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 157, 165, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 166, 167, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 158, 168, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 159, 169, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 170, 171, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 172, 175, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 173, 176, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 174, 177, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 178, 179, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 180, 181, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 183, 190, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 182, 185, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 149, 188, 'marriage', 'active');
INSERT OR IGNORE INTO "union" (tree_id, partner1_id, partner2_id, union_type, status) VALUES (1, 152, 191, 'marriage', 'active');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (1, 0, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (2, 0, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (12, 2, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (13, 2, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (12, 27, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (13, 27, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (3, 1, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (4, 1, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (3, 5, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (4, 5, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (3, 6, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (4, 6, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (15, 3, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (16, 3, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (15, 33, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (16, 33, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (15, 34, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (16, 34, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (15, 35, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (16, 35, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (15, 36, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (16, 36, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 13, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 13, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 128, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 128, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 135, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 135, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 145, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 145, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 153, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 153, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 170, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 170, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (17, 180, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (18, 180, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (21, 18, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (22, 18, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (23, 12, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (24, 12, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (23, 118, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (24, 118, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (23, 119, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (24, 119, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (10, 28, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (5, 28, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (10, 29, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (5, 29, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (7, 8, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (6, 8, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (7, 9, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (6, 9, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (31, 32, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (29, 32, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (33, 38, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (37, 38, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (33, 39, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (37, 39, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (33, 40, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (37, 40, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (41, 42, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (38, 42, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (39, 44, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (43, 44, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (40, 46, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (45, 46, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (34, 48, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (47, 48, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (48, 50, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (49, 50, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (51, 31, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (52, 31, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (53, 10, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (54, 10, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (53, 55, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (54, 55, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (53, 56, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (54, 56, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (53, 66, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (54, 66, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (55, 58, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (57, 58, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (58, 60, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (59, 60, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (61, 59, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (62, 59, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (56, 64, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (63, 64, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (56, 65, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (63, 65, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (67, 68, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (66, 68, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (67, 69, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (66, 69, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (70, 7, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (71, 7, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (70, 72, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (71, 72, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (70, 73, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (71, 73, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (76, 77, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (36, 77, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (76, 78, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (36, 78, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (76, 79, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (36, 79, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (77, 81, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (80, 81, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (77, 82, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (80, 82, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (83, 84, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (81, 84, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (82, 86, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (85, 86, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (78, 88, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (87, 88, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (90, 91, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (79, 91, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 94, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 94, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 95, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 95, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 96, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 96, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 97, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 97, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 98, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 98, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 99, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 99, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (93, 100, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (35, 100, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (101, 102, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (94, 102, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (101, 103, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (94, 103, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (96, 106, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (105, 106, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (96, 107, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (105, 107, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (27, 111, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (110, 111, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (112, 110, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (113, 110, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (112, 114, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (113, 114, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (114, 116, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (115, 116, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (114, 117, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (115, 117, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (118, 121, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (120, 121, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (119, 124, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (123, 124, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (119, 192, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (123, 192, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (124, 126, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (125, 126, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (124, 127, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (125, 127, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (128, 130, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (129, 130, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (131, 132, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (130, 132, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (133, 131, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (134, 131, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (135, 137, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (136, 137, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (135, 138, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (136, 138, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (137, 140, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (139, 140, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (141, 142, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (138, 142, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (141, 143, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (138, 143, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (141, 144, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (138, 144, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (145, 149, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (146, 149, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (145, 152, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (146, 152, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (145, 148, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (147, 148, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (148, 151, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (150, 151, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (153, 155, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (154, 155, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (153, 156, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (154, 156, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (153, 157, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (154, 157, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (153, 158, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (154, 158, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (153, 159, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (154, 159, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (160, 161, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (156, 161, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (160, 162, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (156, 162, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (160, 163, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (156, 163, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (165, 166, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (157, 166, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (171, 172, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (170, 172, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (171, 173, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (170, 173, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (171, 174, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (170, 174, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (174, 178, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (177, 178, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (181, 182, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (180, 182, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (181, 183, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (180, 183, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (190, 184, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (183, 184, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (182, 186, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (185, 186, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (182, 187, 'biological');
INSERT OR IGNORE INTO parent_child (parent_id, child_id, relationship_type) VALUES (185, 187, 'biological');
COMMIT;
PRAGMA foreign_keys = ON;