-- Family Tree Database Seed File
-- Generated: 2026-01-06T03:40:59.088Z
-- Records: 191 people, 71 marriages

BEGIN TRANSACTION;

--------------------------------------------------------------------
-- INSERT ENTITIES (People)
--------------------------------------------------------------------

INSERT INTO entities (id, first_name, last_name, gender) VALUES (88, 'Aarth', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (69, 'Devanshi', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (68, 'Harshil', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (77, 'Hasmukh', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (76, 'Jaswant', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (81, 'Kajal', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (87, 'Kamini', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (80, 'Kirti', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (89, 'Krishna', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (79, 'Pratibha', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (82, 'Priyeash', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (67, 'Rajesh', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (66, 'Rita', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (86, 'Shivaansh', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (78, 'Vijay', 'Amin', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (85, 'Zalak', 'Amin', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (50, 'Aarav', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (111, 'Aayan', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (160, 'Ajay', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (131, 'Amit', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (150, 'Amita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (142, 'Anal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (177, 'Anita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (138, 'Anjana', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (10, 'Atul', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (165, 'Bal Krishna', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (53, 'Balu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (191, 'Bhadresh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (75, 'Bharat', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (134, 'Bharti', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (118, 'Bipin', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (21, 'Channa', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (57, 'Chetna', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (135, 'Chiman', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (16, 'Dahi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (17, 'Dahya', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (83, 'Deep', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (91, 'Deepa', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (56, 'Deepak', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (44, 'Devarsh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (18, 'Dhai', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (124, 'Dharmesh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (41, 'Dhumil', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (122, 'Dhwani', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (36, 'Diyakanta', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (156, 'Falguni', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (3, 'Girish', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (176, 'Girish', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (182, 'Girish', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (28, 'Haimil', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (110, 'Hani', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (178, 'Happy', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (159, 'Harshal', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (46, 'Harshini', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (19, 'Ichhabhai', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (97, 'Illa', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (185, 'Illa', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (93, 'Ishwar', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (121, 'Jay', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (74, 'Jayanti', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (186, 'Jinal (Chaki)', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (100, 'Jitendra', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (84, 'Jiyan', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (139, 'Jyoti', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (24, 'Kamlaba', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (12, 'Kanti', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (153, 'Kanti', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (95, 'Kanu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (112, 'Kanu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (55, 'Kaushik', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (109, 'Kavita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (61, 'Ketan', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (27, 'Keyur', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (43, 'Kinnari', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (11, 'Krishna', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (29, 'Krishna', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (127, 'Krush', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (166, 'Kushi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (35, 'Laliita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (170, 'Lalita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (33, 'Mahendra', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (101, 'Mahesh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (174, 'Mahesh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (117, 'Mahir', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (0, 'Malav', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (6, 'Mamta', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (180, 'Mangu', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (151, 'Manthan', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (119, 'Manu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (133, 'Manu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (25, 'Margabhai', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (130, 'Masum', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (99, 'Mayank', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (173, 'Meena', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (187, 'Meet', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (140, 'Moksh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (155, 'Munni', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (116, 'Naman', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (145, 'Nandu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (164, 'Naresh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (175, 'Naresh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (161, 'Nikki (Anushree)', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (125, 'Nisha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (98, 'Pankaj', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (106, 'Pankti', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (162, 'Param', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (126, 'Pari', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (2, 'Parul', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (45, 'Payal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (49, 'Payal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (107, 'Payal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (168, 'Pinakin', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (188, 'Pinkal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (103, 'Pintu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (34, 'Pradeep', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (62, 'Pragnya', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (114, 'Prakash', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (148, 'Prakash', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (1, 'Prashant', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (40, 'Pratik', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (163, 'Pruthav', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (63, 'Purvi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (105, 'Ragini', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (120, 'Ramila', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (171, 'Rannchod', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (90, 'Rashmikant', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (108, 'Rasik', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (128, 'Rati', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (102, 'Ravin', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (157, 'Rinku', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (158, 'Roma', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (192, 'Rupal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (141, 'Rupesh', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (184, 'Rutvik', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (48, 'Sachin', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (65, 'Sahil', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (38, 'Sangeeta', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (39, 'Sanjay', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (129, 'Sarda', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (146, 'Savita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (5, 'Seema', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (152, 'Sejal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (64, 'Shail', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (136, 'Shanta', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (181, 'Shanti', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (147, 'Sharda', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (115, 'Sheetal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (132, 'Shobhit', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (143, 'Shrujal', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (13, 'Sita', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (183, 'Soha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (54, 'Subhadra', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (37, 'Sudha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (4, 'Sumitra', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (22, 'Surajba', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (154, 'Sushila', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (144, 'Swapnil', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (169, 'Tulsi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (104, 'Usha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (113, 'Usha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (123, 'Usha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (172, 'Usha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (59, 'Vamanshi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (58, 'Varun', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (42, 'Vatsal', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (167, 'Ved', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (92, 'Vedang', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (47, 'Veena', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (179, 'Vidhi', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (96, 'Vijay', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (137, 'Vijay', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (149, 'Vipul', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (189, 'Vishnu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (190, 'Vishnu', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (14, 'Vitthal', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (15, 'Vitthal', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (23, 'Vitthal', 'Patel', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (60, 'Zamyasha', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (94, 'jyoti', 'Patel', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (30, '', 'Purohit', 'unknown');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (70, 'Chandrakant', 'Purohit', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (73, 'Hemant', 'Purohit', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (71, 'Kailash', 'Purohit', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (7, 'Kamlesh', 'Purohit', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (8, 'Mansi', 'Purohit', 'female');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (9, 'Priyank', 'Purohit', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (72, 'Yogesh', 'Purohit', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (31, 'Aditya', 'Shah', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (32, 'Kiaan', 'Shah', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (51, 'Mayank', 'Shah', 'male');
INSERT INTO entities (id, first_name, last_name, gender) VALUES (52, 'Sona', 'Shah', 'female');

--------------------------------------------------------------------
-- INSERT SPOUSAL RELATIONSHIPS
--------------------------------------------------------------------

INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (1, 2);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (12, 13);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (3, 4);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (15, 16);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (17, 18);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (21, 22);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (23, 24);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (5, 10);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (6, 7);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (29, 31);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (33, 37);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (38, 41);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (39, 43);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (40, 45);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (34, 47);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (48, 49);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (51, 52);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (53, 54);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (55, 57);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (58, 59);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (61, 62);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (56, 63);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (66, 67);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (70, 71);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (36, 76);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (77, 80);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (81, 83);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (82, 85);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (78, 87);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (88, 89);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (79, 90);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (91, 92);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (35, 93);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (94, 101);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (95, 104);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (96, 105);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (97, 108);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (98, 109);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (27, 110);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (112, 113);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (114, 115);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (118, 120);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (121, 122);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (119, 123);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (124, 125);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (128, 129);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (130, 131);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (133, 134);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (135, 136);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (137, 139);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (138, 141);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (145, 146);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (145, 147);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (148, 150);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (153, 154);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (156, 160);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (155, 164);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (157, 165);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (166, 167);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (158, 168);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (159, 169);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (170, 171);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (172, 175);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (173, 176);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (174, 177);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (178, 179);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (180, 181);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (183, 190);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (182, 185);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (149, 188);
INSERT INTO spouses (spouse1_id, spouse2_id) VALUES (152, 191);

--------------------------------------------------------------------
-- INSERT PARENT-CHILD RELATIONSHIPS
--------------------------------------------------------------------

INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (1, 0, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (2, 0, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (12, 2, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (13, 2, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (12, 27, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (13, 27, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (3, 1, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (4, 1, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (3, 5, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (4, 5, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (3, 6, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (4, 6, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (15, 3, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (16, 3, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (15, 33, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (16, 33, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (15, 34, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (16, 34, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (15, 35, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (16, 35, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (15, 36, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (16, 36, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 13, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 13, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 128, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 128, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 135, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 135, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 145, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 145, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 153, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 153, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 170, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 170, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (17, 180, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (18, 180, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (21, 18, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (22, 18, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (23, 12, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (24, 12, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (23, 118, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (24, 118, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (23, 119, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (24, 119, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (10, 28, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (5, 28, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (10, 29, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (5, 29, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (7, 8, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (6, 8, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (7, 9, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (6, 9, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (31, 32, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (29, 32, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (33, 38, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (37, 38, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (33, 39, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (37, 39, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (33, 40, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (37, 40, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (41, 42, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (38, 42, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (39, 44, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (43, 44, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (40, 46, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (45, 46, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (34, 48, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (47, 48, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (48, 50, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (49, 50, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (51, 31, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (52, 31, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (53, 10, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (54, 10, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (53, 55, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (54, 55, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (53, 56, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (54, 56, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (53, 66, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (54, 66, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (55, 58, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (57, 58, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (58, 60, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (59, 60, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (61, 59, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (62, 59, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (56, 64, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (63, 64, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (56, 65, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (63, 65, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (67, 68, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (66, 68, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (67, 69, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (66, 69, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (70, 7, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (71, 7, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (70, 72, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (71, 72, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (70, 73, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (71, 73, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (76, 77, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (36, 77, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (76, 78, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (36, 78, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (76, 79, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (36, 79, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (77, 81, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (80, 81, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (77, 82, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (80, 82, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (83, 84, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (81, 84, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (82, 86, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (85, 86, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (78, 88, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (87, 88, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (90, 91, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (79, 91, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 94, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 94, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 95, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 95, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 96, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 96, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 97, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 97, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 98, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 98, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 99, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 99, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (93, 100, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (35, 100, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (101, 102, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (94, 102, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (101, 103, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (94, 103, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (96, 106, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (105, 106, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (96, 107, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (105, 107, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (27, 111, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (110, 111, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (112, 110, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (113, 110, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (112, 114, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (113, 114, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (114, 116, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (115, 116, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (114, 117, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (115, 117, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (118, 121, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (120, 121, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (119, 124, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (123, 124, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (119, 192, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (123, 192, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (124, 126, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (125, 126, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (124, 127, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (125, 127, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (128, 130, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (129, 130, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (131, 132, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (130, 132, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (133, 131, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (134, 131, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (135, 137, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (136, 137, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (135, 138, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (136, 138, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (137, 140, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (139, 140, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (141, 142, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (138, 142, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (141, 143, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (138, 143, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (141, 144, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (138, 144, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (145, 149, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (146, 149, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (145, 152, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (146, 152, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (145, 148, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (147, 148, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (148, 151, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (150, 151, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (153, 155, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (154, 155, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (153, 156, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (154, 156, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (153, 157, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (154, 157, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (153, 158, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (154, 158, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (153, 159, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (154, 159, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (160, 161, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (156, 161, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (160, 162, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (156, 162, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (160, 163, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (156, 163, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (165, 166, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (157, 166, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (171, 172, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (170, 172, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (171, 173, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (170, 173, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (171, 174, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (170, 174, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (174, 178, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (177, 178, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (181, 182, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (180, 182, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (181, 183, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (180, 183, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (190, 184, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (183, 184, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (182, 186, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (185, 186, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (182, 187, 'biological');
INSERT INTO parentages (parent_id, child_id, relationship_type) VALUES (185, 187, 'biological');

COMMIT;

--------------------------------------------------------------------
-- SEED COMPLETE
-- Entities: 191
-- Marriages: 71
-- Parent-child links: 230 (approximate)
--------------------------------------------------------------------
